# Generated by Django 4.2.3 on 2023-08-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_picture_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='images',
            field=models.ImageField(default='media/default.jpg', upload_to=''),
        ),
    ]
